### ISSUE TITLE
Add Slack app to repo

### ISSUE THREAD

**Issue by sgerogia** [microtick/mtzone#11]
Hello.

We would like to get notifications of upcoming releases.

It would be a massive help if we could do it through [Github's Slack](https://slack.github.com/github/v2/install/39583369/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlnZ2VyX2lkIjoiMzQ4MjQwNTI4NDk0NC4xNzYxNTk4MDQ1MDMuZTUwOGY0NzBhYWEwMDkyM2M5M2ViZTMxY2EwMWViZDkiLCJ0ZWFtSWQiOiJUNTY0UFBORVQiLCJjbGllbnREb21haW4iOiJhbGxpbmJpdHMiLCJ1c2VySWQiOiJVMDJFRkEyRjNKOCIsImNoYW5uZWxJZCI6IkMwM0Q5MDBDMkxWIiwidHJpZ2dlcmluZ0FwcCI6IkEwMUJQN1I0S05ZIiwicmVwbGF5Q29tbWFuZCI6dHJ1ZSwiaWF0IjoxNjUxMjI1NjQ1LCJleHAiOjE2NTEyMjkyNDV9.jsoIOmF1RM7Ek0iHO9upKmmd7IoLOAo2Omy8EyYugxg) integration.

Could you kindly install it?

Thank you

**Comment by mark-microtick** [comment]
Getting an error at that url: 

An unexpected error occurred. ref: gh-2a4794ee-a55c-427a-9f91-71f64677d81a

I'll look around to see if I can figure out how to install it.

**Comment by mark-microtick** [comment]
What slack workspace do you need it added to?  If that's your workspace it's something you need to do on your end, I think.

**Comment by mark-microtick** [comment]
Ok - I clicked the link and approved it.  Got stuck redirecting to github, but it might have worked... ?  Let me know....

**Comment by sgerogia** [comment]
It worked!
<img width="526" alt="image" src="https://user-images.githubusercontent.com/1963182/166503408-4c567817-1b85-415a-954b-c44b1b60579a.png">

Many-many thanks!

**Comment by mark-microtick** [comment]
Great, closing this issue.  Glad it worked...
