### ISSUE TITLE
Let's keep the proto files in the source code, as other blockchains in the cosmos ecosystem do

### ISSUE THREAD

**Issue by Raumo0** [microtick/mtzone#4]
The absence of proto files in the source code does not allow convenient use of the source code of microtick fullnodes as a dependency.

Example mapofzones/cosmos-watcher (microtick branch)
https://github.com/mapofzones/cosmos-watcher/runs/3713129146

![image](https://user-images.githubusercontent.com/6114400/134811995-c8ab9d6c-dfc2-410d-ba8e-5799708fa78b.png)

**Comment by joe-bowman** [comment]
This is done here; if you don't mind testing this branch out: https://github.com/joe-bowman/mtzone/tree/v2.0.4

If it works for you, we can get a PR in - otherwise, it should be identical to v2.0.3
