### ISSUE TITLE
Any seed nodes available?

### ISSUE THREAD

**Issue by kucharskim** [microtick/mtzone#7]
Hi, do you guys run any seed nodes, with static IPs and high availability, so we can use it in `config.toml` and `seeds` settings?

Or is there any public RPC, where we could fetch periodically, outside from our own infra, `/net_info` content to generate list of peers.

**Comment by mark-microtick** [comment]
In general the discord validators channel https://discord.com/invite/WxTdDznEkT would be a great place to ask what others are doing.  The main Microtick public seed and several others are available in the stargate-genesis repo https://github.com/microtick/stargate-genesis (although lately they seem to be getting busier, we could use other seed nodes on the network)

**Comment by kucharskim** [comment]
Thanks for info!
